!quiet

!comment(PanDoc makes text paragraphs within list items using autogenerated styles)
!comment(like 'P1', 'P2'... P###.)
!def(generate_list_para_style)
~~~~~~~~~~~~~~~~~~~~~~
<style:style style:name="!1"  style:display-name="!1"  style:parent-style-name="ListPara" style:class="text"/>
~~~~~~~~~~~~~~~~~~~~~~

!comment(Marked list styles)
!comment(like 'P1', 'P2'... P###.)
!def(generate_marked_list_style)
~~~~~~~~~~~~~~~~~~~~~~
<style:style style:name="!1"  style:display-name="!1"  style:parent-style-name="List" style:class="list"/>
~~~~~~~~~~~~~~~~~~~~~~

!comment(Numbered list styles)
!def(generate_numbered_list_style)
~~~~~~~~~~~~~~~~~~~~~~
<style:style style:name="!1"  style:display-name="!1"  style:parent-style-name="Numbering_Template" style:class="list"/>
~~~~~~~~~~~~~~~~~~~~~~
