!quiet
!comment(PanDoc makes text paragraphs within list items using autogenerated styles)
!comment(like 'P1', 'P2'... P###. I'll generate about 30 paragraps styles here)

!def(generate_list_style)
~~~~~~~~~~~~~~~~~~~~~~
<!--
<style:style style:name="!1"  style:display-name="!1"  style:parent-style-name="ListPara" style:class="text"/>
-->
~~~~~~~~~~~~~~~~~~~~~~
